services:
  converter-api:
    build:
      context: .
      dockerfile: src/DocumentConverter.Api/Dockerfile

    image: converter-api:latest
    container_name: converter-api
    restart: unless-stopped

    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_HTTP_PORTS: "8080"
      TZ: "Europe/Istanbul"

      Converter__InputRoot: "/app/data/input"
      Converter__OutputRoot: "/app/data/output"
      Converter__ProcessedRoot: "/app/data/processed"
      Converter__FailedRoot: "/app/data/failed"
      Converter__TempRoot: "/app/data/temp"
      Converter__JobsRoot: "/app/data/jobs"
      Converter__MaxUploadBytes: "52428800"
      Mongo__ConnectionString: "mongodb://host.docker.internal:27017"
      Mongo__DatabaseName: "document_converter"
      Mongo__ConversionJobsCollectionName: "conversionJobs"

    volumes:
      - "./data:/app/data"

    ports:
      - "8088:8080"

    depends_on:
      - converter-worker

  converter-worker:
    build:
      context: .
      dockerfile: src/DocumentConverter.Worker/Dockerfile

    image: converter-worker:latest
    container_name: converter-worker
    restart: unless-stopped

    environment:
      DOTNET_ENVIRONMENT: "Production"
      TZ: "Europe/Istanbul"

      Converter__InputRoot: "/app/data/input"
      Converter__OutputRoot: "/app/data/output"
      Converter__ProcessedRoot: "/app/data/processed"
      Converter__FailedRoot: "/app/data/failed"
      Converter__TempRoot: "/app/data/temp"
      Converter__JobsRoot: "/app/data/jobs"
      Converter__LibreOfficePath: "soffice"
      Converter__ConversionTimeoutSeconds: "120"
      Converter__PollingIntervalSeconds: "30"
      Converter__WorkerId: "converter-worker-1"
      Converter__JobLockSeconds: "300"
      Converter__MaxConcurrentJobs: "1"
      Mongo__ConnectionString: "mongodb://host.docker.internal:27017"
      Mongo__DatabaseName: "document_converter"
      Mongo__ConversionJobsCollectionName: "conversionJobs"

    volumes:
      - "./data:/app/data"
